spring:
  datasource:
    dbcp2:
      url: jdbc:h2:mem:testdb;MODE=MSSQLServer
#      url: jdbc:h2:mem:;MODE=MSSQLServer
      username: ren
      password: password
      driver-class-name: org.h2.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  h2:
    console:
      enabled: true
      path: /h2-console
    profiles:
      active: local

  servlet:
    multipart:
      enabled: true
      location: c:\\upload
      max-request-size: 300MB
      max-file-size: 50MB

  # Naver smtp server 사용
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: cyw960714@naver.com #네이버 아이디
    password: dicarprio9!@ #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
            auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

server:
  port: 8080


